name: Build and push Docker Container

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to GitHub Container Registry
      run: echo ${{ secrets.GH_TOKEN }} | docker login ghcr.io -u ${{ secrets.GH_USERNAME }} --password-stdin

    - name: Build the Docker image
      run: |
        IMAGE_NAME=ghcr.io/${{secrets.GH_USERNAME}}/image-optim:latest
        docker build -t $IMAGE_NAME .

    - name: Push the Docker image
      run: |
        IMAGE_NAME=ghcr.io/${{secrets.GH_USERNAME}}/image-optim:latest
        docker push $IMAGE_NAME
